#!/usr/bin/env bash
# audit-evidence.sh — 產 app 的「稽核證據索引頁」(GitHub Pages)。
#
# 在 GitHub 上，發布證據大半是「原生」的(Security tab、Actions、artifact attestation、
# Dependabot)，不像 GitLab CE 要自建。所以這頁是「稽核員入口」：彙整 live 警報數 +
# 連到原生證據來源 + 控制→NIST SSDF 對照(這層才是 GitHub 沒有、需要人寫的)。
#
# 報告器不是 gate：API 查不到就標 N/A，不讓它掛掉。
set -uo pipefail

OUT="${1:-public}"; mkdir -p "$OUT"
REPO="${GITHUB_REPOSITORY:-ryanGTR/supply-chain-demo}"
SERVER="${GITHUB_SERVER_URL:-https://github.com}"
RUNID="${GITHUB_RUN_ID:-local}"
SHA="${GITHUB_SHA:-local}"
API="${GITHUB_API_URL:-https://api.github.com}"
TOK="${GH_TOKEN:-${GITHUB_TOKEN:-}}"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

gh_count() {  # $1 = api path；回傳陣列長度或 N/A
  [ -n "$TOK" ] || { echo "N/A"; return; }
  local n
  n=$(curl -fsS -H "Authorization: Bearer $TOK" "$API/repos/$REPO/$1" 2>/dev/null | jq 'if type=="array" then length else "N/A" end' 2>/dev/null)
  echo "${n:-N/A}"
}
CS=$(gh_count "code-scanning/alerts?state=open&per_page=100")
DB=$(gh_count "dependabot/alerts?state=open&per_page=100")

icon() { case "$1" in 0) echo '<span class="ok">✓ 0</span>';; N/A) echo '<span class="warn">N/A</span>';; *) echo "<span class=\"bad\">$1</span>";; esac; }

cat > "$OUT/index.html" <<HTML
<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>稽核證據索引 — ${REPO}</title>
<style>
 :root{--ok:#1a7f37;--warn:#9a6700;--bad:#cf222e;--ink:#1f2328;--line:#d0d7de}
 *{box-sizing:border-box} body{font:14px/1.55 -apple-system,Segoe UI,Roboto,"Noto Sans CJK TC",sans-serif;color:var(--ink);margin:0;background:#f6f8fa}
 .wrap{max-width:960px;margin:0 auto;padding:28px 24px} h1{font-size:21px;margin:0 0 4px} .sub{color:#57606a;margin:0 0 20px}
 h2{font-size:15px;border-bottom:2px solid var(--line);padding-bottom:5px;margin:28px 0 12px}
 .cards{display:flex;gap:14px;flex-wrap:wrap} .card{flex:1;min-width:150px;background:#fff;border:1px solid var(--line);border-radius:8px;padding:14px}
 .card .n{font-size:24px;font-weight:700} .card .l{color:#57606a;font-size:12px}
 table{border-collapse:collapse;width:100%;background:#fff} th,td{border:1px solid var(--line);padding:7px 10px;text-align:left}
 th{background:#f6f8fa} a{color:#0969da;text-decoration:none} .ok{color:var(--ok);font-weight:700}.warn{color:var(--warn);font-weight:700}.bad{color:var(--bad);font-weight:700}
 footer{color:#57606a;margin-top:32px;font-size:12px;border-top:1px solid var(--line);padding-top:12px}
</style></head><body><div class="wrap">
<h1>稽核證據索引</h1>
<p class="sub">${REPO} · commit ${SHA:0:8} · run ${RUNID} · 產於 ${NOW}<br>
GitHub 上發布證據大半為原生；本頁是稽核員入口（live 數字 + 原生來源連結 + 控制→監管對照）。</p>

<div class="cards">
 <div class="card"><div class="n">$(icon "$CS")</div><div class="l">Code scanning 未處理警報（SAST/secret/Trivy 的 SARIF）</div></div>
 <div class="card"><div class="n">$(icon "$DB")</div><div class="l">Dependabot 未處理漏洞警報</div></div>
</div>

<h2>原生證據來源（點開即查）</h2>
<table><thead><tr><th>證據</th><th>在哪</th></tr></thead><tbody>
 <tr><td>每次發布的 pipeline 執行</td><td><a href="${SERVER}/${REPO}/actions">Actions</a></td></tr>
 <tr><td>掃描警報（SAST/secret/CVE）</td><td><a href="${SERVER}/${REPO}/security/code-scanning">Security › Code scanning</a></td></tr>
 <tr><td>依賴漏洞 + 自動修補 PR</td><td><a href="${SERVER}/${REPO}/security/dependabot">Security › Dependabot</a></td></tr>
 <tr><td>image + 簽章 + SBOM/SLSA attestation</td><td><a href="${SERVER}/${REPO}/pkgs/container/${REPO##*/}%2Fbackend">GHCR packages</a>（cosign keyless + provenance）</td></tr>
 <tr><td>依賴白名單治理（核可後才爆 CVE）</td><td><a href="https://ryangtr.github.io/dep-policy/">dep-policy 治理儀表板</a></td></tr>
</tbody></table>

<h2>安全控制 → NIST SSDF 對照</h2>
<table><thead><tr><th>控制</th><th>工具</th><th>NIST SSDF</th></tr></thead><tbody>
 <tr><td>依賴 allow-list 審核</td><td>dep-policy + PR/CODEOWNERS</td><td>PW.4, PO.3</td></tr>
 <tr><td>SAST</td><td>Semgrep → code scanning</td><td>PW.7, PW.8</td></tr>
 <tr><td>密鑰掃描</td><td>Gitleaks + push protection</td><td>PW.5, PO.5</td></tr>
 <tr><td>SBOM</td><td>Syft（CycloneDX）</td><td>PS.3</td></tr>
 <tr><td>CVE 掃描 + 持續監控</td><td>Trivy + Dependabot</td><td>RV.1, RV.3</td></tr>
 <tr><td>簽章 + 來源證明</td><td>cosign keyless + SLSA provenance attestation</td><td>PS.2, PS.3</td></tr>
</tbody></table>

<footer>Generated by scripts/audit-evidence.sh · ${NOW} · GitHub-native 證據索引</footer>
</div></body></html>
HTML
echo "audit evidence index → $OUT/index.html (code-scanning=$CS, dependabot=$DB)"
